version: '3'
services:
  node:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/swagger 
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: